# Generated by Django 6.0.5 on 2026-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist_app", "0002_tasklist_manage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
